name: Hprofile Actions
on: workflow_dispatch
jobs:
    Testing:
        runs-on: ubuntu-latest
        steps:
            -  name: checkout code
               uses: actions/checkout@v4

            - name: Set up Java 11
              uses: actions/setup-java@v3
              with:
                java-version: '11'
                distribution: 'temurin'

            - name: Maven Test
              run: mvn test
            
            - name: Checkstyle Analysis
              run: mvn checkstyle:checkstyle

            - name: SonarQube Scan
              uses: sonarqube-quality-gate-action@master
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              with:
                projectBaseDir: .
                args: >
                  -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
                  -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
                  -Dsonar.host.url=${{ secrets.SONAR_URL }}
                  -Dsonar.login=${{ secrets.SONAR_TOKEN }}
                  -Dsonar.java.binaries=target/classes
                  -Dsonar.sources=src/
                  -Dsonar.junit.reportPaths=target/surefire-reports
                  -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
                  -Dsonar.jacoco.reportPaths=target/jacoco.exec


