name: Hprofile Actions
on: workflow_dispatch
env:
  AWS_REGION: us-east-1
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Maven test
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      # Setup java 11 to be default (sonar-scanner requirement as of 5.x)
      - name: Set Java 11
        uses: actions/setup-java@v3
        with:
         distribution: 'temurin' # See 'Supported distributions' for available options
         java-version: '11'

    # Setup sonar-scanner
      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7
   
    ###### Run sonar-scanner
      - name: SonarQube Scan
        run: |
          echo "SONAR_URL: ${{ secrets.SONAR_URL }}"
          echo "SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}"
          echo "SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}"
          sonar-scanner \
            -Dsonar.host.url=${{ secrets.SONAR_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.sources=src/ \
            -Dsonar.junit.reportsPath=target/surefire-reports/ \
            -Dsonar.jacoco.reportsPath=target/jacoco.exec \
            -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml \
            -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/
        

  BUILD_AND_PUBLISH:
    runs-on: ubuntu-latest
    needs: Testing
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Build and publish to SonarQube
        run: echo "Build and publish to SonarQube"

      - name: Update applications.properties file
        run: |
          sed -i "s/jdbc.username.*/jdbc.username=${{ secrets.RDS_USER }}/" src/main/resources/application.properties
          sed -i "s/jdbc.password.*/jdbc.password=${{ secrets.RDS_PASS }}/" src/main/resources/application.properties
          sed -i "s/jdbc.url.*/jdbc.url=${{ secrets.RDS_ENDPOINT }}/" src/main/resources/application.properties

      - name: Build and publish to AWS ECR
        uses: appleboy/docker-ecr-acyion@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_REGION }}
          repository: actionsrepo
          tags: latest,${{ github.rub_number }}
          daemon_off: false
          dockerfile: ./Dockerfile
          context: .